gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Colosseum Isle!\p"
	.string "This island is home to the \n"
	.string "biggest championship in the world.\p"
	.string "Let's get you registered!\p"
	.string "$"


gText_Birch_AndYouAre::
	.string "Tell me a little about yourself.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN},\n"
	.string "and where are you from?.\l"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "You must qualify for the main \n"
	.string "event!\p"
	.string "Seek out the 9 stadiums\n"
	.string "spread out around the island,\l"
	.string "and prove yourself at each one.\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Good luck! This won't be easy.\p"
	.string "$"
